### ISSUE TITLE
puppet version

### ISSUE THREAD

**Issue by slima** [prozeta/puppet-powerdns_recursor#2]
I think plugin works with puppet 3.4.3

**Comment by liqw33d** [comment]
@slima : do you have an environment with mentioned puppet 3.4.3?
If yes I'll be happy if you test it and give me response.
If all goes well I can update this check https://github.com/prozeta/puppet-powerdns_recursor/blob/master/manifests/init.pp#L37 into new version of module.

**Comment by liqw33d** [comment]
closing this since puppet 3.4.3 isn't supported.
