### ISSUE TITLE
puppet ntp mopdule

### ISSUE THREAD

**Issue by fmontaldo** [prozeta/puppet-powerdns_recursor#3]
Hi,

I configure the puppet module in red hat satellite following this guide:

http://www.areyouroot.com/2015/01/red-hat-satellite-6-puppet-what-hell-do.html

As per that ocnfigureation the moudle will tell me if the server got syncronized the time?. ALso I want to know if the puppet mode can pussh from the satellite side to the agent to pull the ntpo clock.

Regards

**Comment by liqw33d** [comment]
@fmotnaldo : I think your problem isn't related to powerdns_recursor module, so closing this one.
