### ISSUE TITLE
Apache License Violation

### ISSUE THREAD

**Issue by jmkeyes** [prozeta/puppet-powerdns_recursor#4]
It appears that a significant portion of this module's code has been lifted directly from the PowerDNS module I've published to Github and the Puppet Forge.

The module I've published is licensed under the Apache 2.0 license which forbids the removal and/or alteration of copyright/license notices.

I'd appreciate it if you could restore the original copyright notice(s) and provide some attribution for the code you've used.

Source(s): 
* [`jmkeyes/powerdns` "Initial Commit" - May 27, 2015 - df6b980e](https://github.com/jmkeyes/puppet-powerdns/commit/df6b980eb08abfbf8bb197c74ddf49b1a808246c)
* [`prozeta/puppet-powerdns_recursor` - "Initial Commit" - Aug 22, 2016 - 9d83f656](https://github.com/prozeta/puppet-powerdns_recursor/commit/9d83f656f0add71941d88f50a476cf2f92bd9d84)

Thank you!

**Comment by liqw33d** [comment]
Sorry for this and thanks for the report.
https://github.com/prozeta/puppet-powerdns_recursor/commit/c36c2d05fa23697cbb348f917275d4a07009ac34 restores the original notices.
updated README contains reference to the original module.
And new module version with this will be released at forge very soon.
Is it okay for you now?

**Comment by jmkeyes** [comment]
Absolutely! Thank you!

My original use case for developing the module didn't include the PowerDNS recursor but I see there's interest in managing it with Puppet.

If you'd like to, please submit an issue or a PR to add PowerDNS recursor support.

I'd be happy to help maintain it for you.
